## create Deployment for NOde-16-ALPHINE

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2  # Set the desired number of replicas
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: node:16-alpine  # Use the node:16-alpine Docker image
          ports:
            - containerPort: 3000  # Set the port your Node.js app is listening on
##Define service with Loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80  # Exposed port in the Service
      targetPort: 3000  # Port your Node.js app is listening on in the container
  type: LoadBalancer  # Use LoadBalancer if you want to expose externally
