---
- name:  sample_yolo_playbook
  hosts:  all
  become:  yes
  roles:
    - docker-installation
    - clone-repo

  tasks:
    - name: run docker docker-compose.yaml
      command: docker compose up -d
      args:
        chdir: /home/vagrant/yolo
