apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: grc.io/kubernetes-395317/yolo-backend:1.1.0
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /api/products
              port: 5000